project:
  type: book
  output-dir: docs

book:
  title: "ESR Technical Documentation test"
  author: "Greg Williams, Isaac Schroeder, Chris Dailey, etc"
  date: "1/25/2025"
  chapters:
    - index.qmd
    - Introduction.qmd

bibliography: esr-bibliography.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



