project:
  type: book
  output-dir: docs

book:
  title: "ESR Technical Documentation test"
  author: "Greg Williams, Isaac Schroeder, Chris Dailey, etc"
  date: "1/25/2025"
  chapters:
    - index.qmd
    - Introduction.qmd
    - part: General Methods
      chapters:
      - DataCodeAccess.qmd
      - TimeSeriesQuadplots.qmd
      - TrendAnalysis.qmd
      - SurveyData.qmd
      - ConceptualModels.qmd
      - Glossary.qmd
      
    - part: Focal Components of Ecological Integrity
      chapters:
      - Copepods.qmd
      - Krill.qmd
      - DungenessCrabMegalopae.qmd
      - NCCForage.qmd
      - CCCForage.qmd
      - SCCForage.qmd
      - CPSSurvey.qmd
      - SalmonStoplightTables.qmd
      - ChinookSalmonEscapementColumbia.qmd
      - ChinookSalmonEcosystemCalifornia.qmd
      - GroundfishStockAbundance.qmd
      - JuvenileGroundfish.qmd
      - GroundfishPortAvailability.qmd
      - HMSDiets.qmd
      - SeaLionProductivity.qmd
      - SeabirdProductivity.qmd
      - SeabirdDensity.qmd
      - SeabirdMortality.qmd
      - HarmfulAlgalBlooms.qmd
      
    - part: Fishing and Non-Fishing Human Activities
      chapters:
      - FisheryLandings.qmd
      - SpatialInteractionsOceanUse.qmd

    - part: Human Wellbeing
      chapters:
      - SocialVulnerability.qmd
      - FleetIncomeDiversification.qmd
      - NonFisheryIncomeDiversification.qmd
      - FisheryRevenueConcentration.qmd
      - FisheriesParticipationNetworks.qmd
      
bibliography: esr-bibliography.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



