project:
  type: book
  output-dir: docs

book:
  title: "CCIEA ESR Technical Documentation"
  subtitle: "California Current Integrated Ecosystem Assessment"
  author: "Lynn DeWitt, Greg Williams, Isaac Schroeder, Chris Dailey, Nick Tolimieri"
  date: last-modified
  navbar:
    background: "#276189"
    search: true
    logo: "figures/logo-5.png"
    logo-alt: "California Current Integrated Ecosystem Assessment Website"
    logo-href: "https://www.integratedecosystemassessment.noaa.gov/regions/california-current"
  sidebar: 
    search: false
    collapse-level: 1
  chapters:
    - index.qmd
    - Introduction.qmd
    - part: General Methods
      chapters:
      - DataCodeAccess.qmd
      - TimeSeriesQuadplots.qmd
      - TrendAnalysis.qmd
      - SurveyData.qmd
      - ConceptualModels.qmd
      - Glossary.qmd
      
    - part: Climate and Oceans
      chapters:
      - ONI.qmd
      - PDO.qmd
      - NPGO.qmd
      - NPH.qmd
      - SST.qmd
      - SSTspatial.qmd
      - MarineHeatwaves.qmd
      - HabitatCompressionIndex.qmd
      - DepthTimeTempGlider.qmd
      - Upwelling.qmd
      - DissolvedOxygen.qmd
      - OceanAcidification.qmd
      - SnowWaterEquivalent.qmd
      - MaximumStreamTemperature.qmd
      - Streamflow.qmd
      
    - part: Focal Components of Ecological Integrity
      chapters:
      - Copepods.qmd
      - Krill.qmd
      - NCCForage.qmd
      - CCCForage.qmd
      - SCCForage.qmd
      - CPSSurvey.qmd
      - JuvenileSalmon.qmd
      - SalmonStoplightTables.qmd
      - ChinookSalmonEscapementColumbia.qmd
      - ChinookSalmonEcosystemCalifornia.qmd
      - GroundfishStockAbundance.qmd
      - JuvenileGroundfish.qmd
      - GroundfishPortAvailability.qmd
      - HMSRecruitmentSSB
      - HMSDiets.qmd
      - SeabirdProductivity.qmd
      - SeabirdDensity.qmd
      - SeabirdMortality.qmd
      - SeabirdDiet.qmd
      - SeaLionProductivity.qmd
      - WhaleEntanglement.qmd
      - HarmfulAlgalBlooms.qmd
      
    - part: Fishing and Non-Fishing Human Activities
      chapters:
      - FisheryLandings.qmd
      - FisheryRevenue.qmd
      - TrawlBottomContact.qmd
      - OtherHumanActivities
      - SpatialInteractionsOceanUse.qmd

    - part: Human Wellbeing
      chapters:
      - SocialVulnerability.qmd
      - FleetIncomeDiversification.qmd
      - NonFisheryIncomeDiversification.qmd
      - FisheryRevenueConcentration.qmd
      - FisheriesParticipationNetworks.qmd
      
bibliography: esr-bibliography.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



