# Central California Current Forage
{{< include _setup.qmd >}}

**Description** 
The Central CCE forage survey (known as the Rockfish Recruitment and Ecosystem Assessment Survey, RREAS) samples much of the West Coast each May to mid-June, using midwater trawls sampling between 30 and 45 m depths during nighttime hours. The survey targets young-of-the-year (YOY) rockfish species and a variety of other YOY and adult forage species, market squid, adult krill, and gelatinous zooplankton. Juvenile rockfish, anchovy, krill, and market squid are among the most important prey for CCE predators [@szoboszlai2015forage]. Time series presented here are from the "Core Area" of that survey, centered off Monterey Bay. Catch data were standardized by using a delta-GLM to estimate year effects while accounting for spatial and temporal covariates to yield relative abundance indices, shown with their approximate 95% confidence limits [@santora2021diverse]. This modeling approach was adopted in recent reports to reduce bias in 2020, when sampling effort and spatial coverage was severely constrained by the COVID-19 pandemic.

Pelagic forage data from the Central CCE were provided by J. Field, T. Rogers, K. Sakuma, and J. Santora, NMFS/SWFSC, from the SWFSC Rockfish Recruitment and Ecosystem Assessment Survey (https://go.usa.gov/xGMfR). Similarity analysis and cluster plot by A. Thompson, NMFS/SWFSC.

**Indicators**

```{r}
#| echo: false
#| results: 'asis'
erddap_id='cciea_EI_FBC'
one_id_byquery(erddap_id,"Species")
get_erddap_link(erddap_id)
```


**References**

