# Chinook Salmon Ecosystem Conditions - California

**Description**. Central Valley Fall Chinook salmon stoplight table: In the 2019-2020 ecosystem status report (REFERENCE), we introduced a relatively simple “stoplight” table of ecosystem indicators that were shown by @friedman2019modeling to be correlated with returns of naturally produced Central Valley Fall Chinook salmon. In an updated stoplight chart for adult Fall Chinook salmon returning to the Central Valley in 2024, the focal ecosystem indicators are: spawning escapement of parent generations; egg incubation temperature between October and December at Red Bluff Diversion Dam (Sacramento River); egg thiamine concentrations based on averages of samples collected from Central Valley fall run hatchery programs; median flow in the Sacramento River in the February after fry emergence; and a marine predation index based on the abundance of common murres at Southeast Farallon Island and the proportion of juvenile salmon in their diets. Reflecting discussions with the SSC-ES in September 2020, we emphasize that this stoplight chart is strictly qualitative and contextual decision-support information. Qualitative descriptors (color-coded terms like “very poor”) are based on recent time series and on expert opinion of how a given indicator relates to quantitative analysis of the relationship between the indicator and life-stage specific survival (see Figure 5 in Friedman et al. 2019). For example, in the stoplight Table flows rated "very low" (\<7,000 cfs) are consistent with \<25% rearing/outmigration survival rates, while the flows rated “low” (7,000 to 20,000 cfs) were consistent with 25-50% outmigrant survival (see Fig. 5 in, Friedman et al. 2019). Egg incubation temperatures in the Table were consistent with egg-to-fry survival ranging from \~50% (which we rated as “suboptimal”) to 0% at \> 13 C (“very poor/cohort failure”). We continue to refine these qualitative categories for future reports so that their basis is more explicit.

The escapement descriptor is a qualitative evaluation of how natural-area escapement of a parent generation relates to the natural area + hatchery escapement goal of 122,000– 180,000 fish, with 122,000 spawners as the SMSY target (PFMC 2022d). Natural area escapement is relevant to the stoplight table as an indicator of total natural area egg production [@munsch2020potential]. However, the qualification of this indicator requires future research. Obviously, using a natural+hatchery target as the qualifier for natural-only escapement is problematic. Perhaps more importantly, the SSC and STT have both recommended research and reconsideration of the Sacramento River fall Chinook SMSY objective (PFMC 2022e,f), and @satterthwaite202approach has concluded that an escapement of 122,000 adults is insufficient to maximize natural production. We have not been able to fully address the SSC and SST comments yet.

The qualitative nature of this stoplight table is in part due to the fact that some of the parameters used by @friedman2019modeling were estimated using information from both natural-origin and hatchery-origin fish, and while it is reasonable to assume that true parameter values would be similar, given correlations between natural and hatchery escapements, additional data specific to natural-origin fish are likely necessary in order to improve model fits, evaluate other potential covariates, and support adequate testing of model predictive skill.

\[include here Table J.1 which documents the habitat indicators, definitions, and key references\]

**Indicator Category** Ecological Integrity

**Data Steward** Greene and Munsch; correigh.greene@noaa.gov, stuart.munsch@noaa.gov

**Additional Information** The indicators representing Ecosystem conditions for California Chinook salmon have been shown in previous studies or were proposed in rebuilding plans to be strongly related with life-stage specific Chinook salmon productivity, and these studies helped determine expected directionality of indicators with stock productivity (see below and Harvey et al. 2020 for additional justification). Four of the five broad categories of indicators in the stoplight charts align with the simpler stoplight chart for Central Valley fall Chinook salmon presented in the main body of this report (Table 3.2): Adult Spawners, Incubation conditions, Freshwater / Estuarine Residence conditions, and Marine Residence conditions (for the first year of marine residence). The fifth category of indicators, Hatchery Releases, expands the scope of these tables relative Table 3.2, which focuses only on natural-area fish. The habitat indicator charts also share qualities with the stoplight chart developed for Columbia Basin Chinook salmon and Oregon coast coho salmon (Table 3.1) by including regional and basin-scale oceanographic indicators as part of early marine residence conditions. Data on krill off northern California are also presented within the table for KRFC.

The indicators in Table J.1 and in the stoplight tables above have undergone several important adjustments from previous reports:

Updates to SRFC and KRFC include changes in some indicators to ensure more reliable and timely data capture. However, updates of many indicators in 2023 remain challenging due to delays in posting of online datasets, resulting in several indicators that could not be updated for this year’s report and preliminary estimates for several others. These challenges underscore the importance of including multiple indicators, highlight the potential fragility of these annual summaries, and point to the importance of many individuals for maintaining the databases required for summarizing habitat indicators.

Recent analysis of krill off northern California have revealed that krill length is a much better indicator than krill biomass for predicting productivity of Klamath Fall run, so we have substituted length for this indicator.

CVSC differs from SRFC not only in migration timing but also in their behavior and spatial distribution. Habitat indicators reflect these differences, by characterizing early upstream migration starting in February, holding in pools through the summer, and spawning in a small number of creeks in the late summer and fall. Adult numbers focused on spawner counts in Butte, Mill, and Deer Creeks. Butte Creek spawners migrate from the Sacramento River through Sutter Bypass to Butte Creek, and outmigrants may rear within Sutter Bypass during outmigration. Hence, flow and temperature metrics relied on gages from these systems in addition to the Sacramento mainstem, and Sutter Bypass inundation instead of Yolo Bypass. Finally, the sole hatchery for CVSC is from Feather River, so releases and timing metrics focused on data from just this hatchery.

The stoplight tables are categorized from favorable to poor conditions using the same approach as described for the Northern California Current salmon indicator stoplight table. Specifically, after indicator datasets were collected, all indicators were “directionalized” to account for their expected relationships with stock productivity (based on the “Effect” column in (Table J.1) and converted into standardized values. These values are reported in the stoplight tables above, with colors delineating statistically meaningful departures (\>2 s.d.) toward poorer (warm shades) or more productive (cool shades) conditions compared to near-average years (within ±1 s.d., yellow). The main difference for the tables shown here relative to Columbia River salmon stoplight tables is that we have not yet determined a fixed historic reference period for the SRFC, KRFC and CVSC tables, due in part to missing data from one or more indicators in large portions of the time series.

Habitat Indicator Descriptions. Adults returning and migrating to spawning grounds: Spawning adults set the cohort size [@friedman2019modeling] and potential for density-dependent habitat limitations at future life stages  [@munsch2020potential], so we incorporated estimated escapements from PFMC preseason forecasts. Adults must navigate multiple potential barriers to reach spawning grounds, including low river flows and high temperatures at the end of summer. We used flow and temperature measurements from the lower portions of the Sacramento and Klamath Rivers in September and October. In the Sacramento River, adults must also navigate the channel network of the delta, and the rebuilding plan proposed examining potential effects of the Delta Cross Channel as a migration barrier. We used the proportion of time the Cross Channel was closed in September and October as the indicator.

Indicators for adult migrations differ for CVSC due to their early migration timing (February to May), spring-summer holding in pools, and spawning in a small number of Sacramento tributaries. We restricted the enumerated spawner abundance to Deer, Mill, and Butte Creeks, for which records were consistently maintained throughout the 1983-present period of record. To fill in data gaps of spawner counts for Butte Creek (the largest spawning population) to complete the retrospective time series to the 1983 brood year, we used predictions from regressions of Butte Creek spawner counts and snorkel surveys. Flows and temperatures during holding were restricted to the river with the greatest spawner abundance (Butte Creek). In addition, CDFW conducts estimates of pre-spawn mortality which we added as an indicator due to CVSC’s exposure to warm in-river conditions.

Incubation to emergence: After spawning, incubating eggs may be subject to dewatering in the river (Jager et al. 1997) and are sensitive to high temperatures  [@friedman2019modeling]. For SRFC, the river flow indicator was derived from the seven-day 10th percentile of flow for the Sacramento River from October to December at Bend Bridge near Red Bluff. For CVSC, we used similar flow conditions for Butte Creek. For KRFC, dewatering previously was observed in various tributaries of the Klamath. Hence, minimum flows from four gages (Klamath at Iron Gate, Scott River, Shasta River, and Trinity River at Lewiston Dam) were used, and the index was calculated from the average of standardized flow values. Incubation temperature records were obtained for all three river systems, albeit for a much shorter time series in the Klamath. SRFC incubation temperature estimates are from Red Bluff Diversion Dam (data in Friedman et al. 2019), CVSC records are from Butte Creek, and Klamath records are from Seiad Valley. Egg-fry productivity as measured by migrants per spawner were initiated in the early 2000s for all stocks.

Freshwater and estuary residence: During migration to the ocean, fall Chinook salmon stocks take advantage of temporary residence in riverine and estuary habitats before transitioning to marine environments. We used a variety of indicators of habitat conditions during this stage. Freshwater conditions are set by precipitation and spring air temperatures, both of which influence snowpack salmon runs and river flow (Munsch et al. 2019) in both tributaries (important for CVSC in particular) and mainstem. In turn, flows from December to May (and their temporal variation) set conditions for rearing in river and estuary systems as fish move downstream, and have been linked to freshwater (Munsch et al. 2019) and life-cycle productivity (Michel 2019, Friedman et al. 2019). Higher flows also determine access to floodplain rearing in reaches such as the Yolo Bypass for SRFC (Limm and Marchetti 2009) and Sutter Bypass for CVSC, as well as the potential to flush polychaete hosts of the parasite Ceratomyxa shasta that infects juvenile salmon during outmigration (Jordan 2012). Flows also determine the outflow through the Sacramento delta (Reis et al. 2019), which can influence estuarine rearing opportunities [@munsch2020potential]. To shift freshwater flows to pumping facilities, the Bureau of Reclamation opens the Delta Cross Channel, and this pathway can entrain salmon in pumps or otherwise expose them to higher mortality (Perry et al. 2013).

Magnitude and timing of hatchery releases: While much of the habitat indicators focus on natural-area fish, hatchery releases make up a significant contribution of each run and may also contribute to density dependence. We therefore included the annual total of hatchery releases, using data from up to four SRFC hatcheries on the Sacramento (San Joaquin hatcheries were not included), the Feather River hatchery for CVSC, and Trinity and Iron Gate hatcheries in the Klamath. While hatchery-origin juveniles are also sensitive to the conditions natural-origin juveniles face, they are generally raised until they are primed for rapid migration. Following concepts of match-mismatch theory (Cushing 1990), we compared release date with the date of peak spring flow in freshwater and the spring transition in the ocean, as @satterthwaite2014match showed that both timing of release relative to the spring transition and overall later release timing were positively correlated with survival rates. Fates of hatchery fish may be a consequence of release location (Sturrock et al. 2019), including locations external to the Sacramento River system, so we also included the proportion of releases that were seaward of Sherman Island in the lower delta.

Marine residence: Marine residence of 1 to 5 years completes the life cycle for fall run Chinook salmon populations. While a broad number of marine habitat indicators have been examined (Wells et al. 2008), we focused on a limited subset of possible indicators representing initial set-up of ocean entry conditions (March-May), including sea surface temperature, the North Pacific Index, and North Pacific Gyre Oscillation. We also included an index of predation by common murres nesting at Southeast Farallon Island, which was a strong predictor in @friedman2019modeling. Unfortunately, this indicator currently cannot be updated quantitatively. On the positive side, we have updated the krill prey indicator for Klamath River fall Chinook salmon from biomass to average length to better reflect stronger correlations with recruits per spawner. Where indicators were averaged to obtain a marine habitat conditions score, hatchery release timing relative to the spring transition was also included as a marine habitat condition.

**References**
