# CPS Survey

**Description** 
Acoustic-trawl method (ATM) surveys have been used by the NOAA Southwest Fisheries Science Center in most years since 2006 to map the distributions and estimate the abundances of coastal pelagic fish species (CPS) in the coastal region from Vancouver Island, Canada, to San Diego, California [@zwolinski2014building; @stierhoff2024distribution]. The surveys cover waters to at least the 1,000-fathom (1829-m) isobath, or 65 km from shore. 

The five most abundant CPS in this domain are Northern Anchovy, Pacific Herring, Pacific Sardine, Jack Mackerel, and Pacific Mackerel. The biomass of Pacific Sardine is calculated separately for the northern and southern stocks based on oceanographic habitat, spatial separation, and demographic structure [@zwolinski2024updated]. The ATM combines data from echosounders which record CPS echoes, and trawls which produce information about the composition, sizes, and ages of the fishes. This survey also samples the densities of CPS eggs at 3-m depth using a continuous underway fish egg sampler (CUFES) mounted on the ship’s hull.

CPS surveys typically span the area between Cape Flattery, WA and San Diego,CA but in some years also include Vancouver Island, Canada (2015-2019) and portions of Baja CA (2021-2022).

**Indicator Category** Ecological Integrity

**Data Steward** K. Stierhoff, NMFS/SWFSC (kevin.stierhoff at noaa.gov) and J. Zwolinski, UCSC and NMFS/SWFSC

**Institution** NOAA SWFSC

**Additional Information**
Data are collected and analyzed by K. Stierhoff and J. Zwolinski, who submit figures and plots to the CCIEA editorial team based on an early version of the annual CPS Acoustic Trawl survey report (preliminary until published, and subject to change), which is ultimately published as a NOAA Technical Report. 
For recent examples, see:  
NOAA Technical Memorandum NMFS-SWFSC-676. https://doi.org/10.25923/77kp-ww39; 
NOAA Technical Memorandum NMFS-SWFSC-683. https://doi.org/10.25923/40x3-b146

**References**

::: {.sectionrefs}
:::
