
# CUGN glider time-depth

```{r}
#| echo: false
#| message: false
#| eval: true
cciea_yr <- 2024

```

**Description** Time versus depth profiles of water temperatures off of Monterey (66), Pt Conception (80), and north of San Diego (90) demonstrate the extent of recent warm and cool anomalies into the water column, as well as spatial and temporal dynamics of these anomalies.

**Metafile name** Not in CCIEA Metadatabase

**Indicator Category** Climate and Ocean Drivers

**Data Steward** Schroeder

**Erddap Dataset ID** NA

**CCIEA timeseries ID** NA

**Region** Lines 66, 80, 90

**Public availability statement** Source data are publicly available.

**Data sources** Netcdf files of the three lines can be downloaded from <https://spraydata.ucsd.edu/projects/CUGN/>. The data downloaded are temperature anomalies created by CUGN.

**Additional Information** The temperature anomaly data provided in the netcdf file has data across the line at 5 m intervals over 0-500 m and distances at 5 km from the coat out to the end of the line (66=400 km, 80=365 km, 90=530 km). Distance can be averaged using Python xarray to select specific distance ranges and then averaging over the distances. The time interval of the netcdf file is 10 days.
