---
bibliography: esr-bibliography.bib
---

# Fisheries Participation Networks

**Description** 
Vessel-level fisheries participation networks (FPNs] provide a visual representation of the portfolio of fisheries that are economically-important to individual vessels within a port group and represent how diversified harvest portfolios create connections between fisheries [@fuller2017characterizing; @fisher2021climate]. FPNs have shown how West Coast networks change over time, how groundfish fisheries are connected to other fisheries in different IO-PAC port groups [@harvey2022cciea], and the vulnerability of West Coast port groups to future shocks to salmon fishing, based on economic dependence (a measure of sensitivity) and a resilience index based on fisheries connectivity (a measure of adaptive capacity) (Harvey et al. 2023). More recently, we compare the number of active salmon vessels and the revenue of commercial salmon vessels between two periods (2017-2022 and 2022-2023) for West Coast port groups.

As fishers diversify their harvest portfolios, they create connections between fisheries, even when ecological links between the target species are weak or absent. In previous reports [@harvey2021ecosystem; @harvey2022cciea; @harvey2023cciea; @leising2024cciea], we used fisheries participation networks [@fuller2017characterizing; @fisher2021climate] as a way to represent this information about how fisheries are connected through shared participation patterns. In these networks, fisheries are depicted as nodes, and pairs of nodes are connected by lines called 'edges' that integrate information about vessels participating in both fisheries. Changes in network structure over time reflect changes in the ecology of adjacent coastal waters, as well as the legacy of management, markets, and other factors.


**Indicator Category** Human Wellbeing

**Data Steward** Samhouri; jameal.samhouri\@noaa.gov

**Additional Information**
Data are collected and analyzed independently by J. Samhouri, who submits unpublished figures and plots to the CCIEA editorial team.

**Data sources** 
The networks are derived from landings receipts and summarized annually from week 46 in one year through week 45 in the following year (e.g., November 2020 to November 2021) to capture the beginning of the Dungeness crab fishing season. Fisheries landings data were retrieved from the Pacific Fisheries Information Network (PacFIN; http://pacfin.psmfc.org) database. We note that in Washington, fish tickets include a port assigned based on the actual port of landing or derived from the license database; prior to 2018, most port data were derived.

**Data extraction** To focus the analysis on vessels that derive a substantial amount of income from commercial fishing, we include only vessels that generate at least \$5,000 annually in total fisheries revenue. In addition, vessels must generate at least \$500 of revenue from a given fishery (node) to be included as participants in that fishery. We assume that economically-important fisheries are those that contribute to at least a median of 10% of the annual revenue of associated vessels. Vessels are represented in all port groups for which their landings meet these conditions. To maintain confidentiality, we include only fisheries with at least three vessels participating in a port group.

In network graphs, node size represents the median proportional contribution of a fishery to annual vessel-level revenue; it is scaled relative to the fishery with the maximum median proportional contribution to annual vessel-level revenue in each network, summarized by port group. Therefore, node sizes are not comparable across port groups, only within them. The edges connecting pairs of nodes indicate that vessels participate in both fisheries, and the widths of these edges scale with the number of vessels exhibiting this behavior, as well as the total amount and evenness of revenue generation from each pair of fisheries. As with node sizes, edge widths are not comparable across port groups, only within them.

**Data analysis**

**References**

::: {.sectionrefs}
:::

