# Fleet Income Diversification
{{< include _setup.qmd >}}


**Description** 
Catches and prices from many fisheries exhibit high interannual variability, leading to high variability in fisher’s revenue, but variability can be reduced by diversifying activities across multiple fisheries or regions [@kasperski2013income]. Individuals may have good reasons to specialize, including reduced costs or greater efficiency; thus while diversification may reduce income variation, it does not necessarily promote higher average profitability. We use the Effective Shannon Index (ESI) to examine diversification of fishing revenue for more than 28,000 vessels fishing off the West Coast and Alaska over the last 40 years. The ESI increases as revenues are spread across more fisheries, and as revenues are spread more evenly across fisheries; ESI = 1 when a vessel’s revenues are from a single species group and region; ESI = 2 if revenues are spread evenly across 2 fisheries; ESI = 3 if revenues are spread evenly across 3 fisheries; and so on. If revenue is not evenly distributed across fisheries, then the ESI value is lower than the number of fisheries a vessel enters.

Diversification can take other forms. Spreading effort and catch over the year, or simply fishing more weeks of the year, can both increase revenue and decrease interannual variation of revenue just as species diversification does. In fact, @abbott2023species showed that reductions in revenue variation associated with species diversification can be explained mainly by increased temporal diversification, which can be achieved by fishing in multiple fisheries but also by fishing for more weeks of the year in a single fishery. Effective Shannon Index can also be used to examine how widely and evenly vessel revenues are spread across weeks of the year as an indicator or temporal diversification. Like the species diversification metric, this index increases the more weeks of the year a vessel has revenue and the more evenly that revenue is distributed across weeks. A vessel fishing 15 weeks of the year with the same revenue each of those weeks would have a temporal ESI of 15, and that number would decline as revenue is spread less evenly over the 15 weeks.


```{r}
#| echo: false
#| results: 'asis'
erddap_id='cciea_HD_ESI_VESS'
one_id_byquery(erddap_id,"Indicators")
get_erddap_link(erddap_id)
```

**References**
