# Harmful Algal Blooms

**Description** 
Harmful algal blooms (HABs) of diatoms in the genus *Pseudo-nitzschia* have been a recurring concern along the West Coast. Certain species of *Pseudo-nitzschia* produce the toxin domoic acid, which can accumulate in filter feeders and extend through food webs to cause harmful or lethal effects on people, marine mammals, and seabirds [@lefebvre2002sanddabs; @mccabe2016unprecedented]. Because domoic acid can cause amnesic shellfish poisoning in humans, fisheries that target shellfish (including razor clam, Dungeness crab, rock crab, and spiny lobster) are delayed, closed, or operate under special orders or health advisories when domoic acid concentrations exceed regulatory thresholds for human consumption. Fishery closures can cost tens of millions of dollars in lost revenue, and cause a range of sociocultural impacts in fishing communities [@dyson2010regional; @ritzman2018economic; @holland2020delay; @moore2020harmful], including a “spillover” of fishing effort into other fisheries.

Ocean conditions associated with marine heatwaves, El Niño events, or positive PDO regimes may further exacerbate domoic acid toxicity and fishery impacts, and domoic acid toxicity tracks anomalies of southern copepod biomass (Fig. 3.1) [@mccabe2016unprecedented; @mckibben2017climatic]. The largest and most toxic HAB of *Pseudo-nitzschia* on the West Coast occurred in 2015, coincident with the 2013-2016 marine heatwave, and caused the longest-lasting and most widespread HAB-related fisheries closures on record [@mccabe2016unprecedented; @moore2019index; @trainer2020pelagic]. Closures and delays in the opening of West Coast crab fisheries resulted in the appropriation of \>\$25M in federal disaster relief funds [@mccabe2016unprecedented].

According to thresholds set by the U.S. Food and Drug Administration, domoic acid levels ≥20 parts per million (ppm) trigger actions for all seafood and tissues except Dungeness crab viscera, for which the level is \>30 ppm (California applies this to rock crab viscera as well) [@FDA2011fish]. Under evisceration orders, Dungeness crab can be landed when the viscera exceeds the threshold but the meat does not, provided that crab are eviscerated by a licensed processor. Oregon was the first West Coast state to pass legislation allowing evisceration, in November 2017, followed by California in October 2021. Washington adopted an emergency evisceration rule in February 2021, and is considering legislation to grant long-term authority for issuing evisceration orders.

**Indicator Category** Ecological Integrity

**Data Steward** S. Moore, NMFS/NWFSC (stephanie.moore at noaa.gov); 

**Additional Information**
Domoic acid data are collected from state partners and analyzed independently by S. Moore and C. Free, who submit unpublished figures and plots to the CCIEA editorial team. Data are plotted as monthly maximum domoic acid concentrations for both razor clams and Dungeness crab viscera relative to management thresholds (20 ppm - clams; 30 ppm - crabs).

**Data sources** 
Domoic acid data are provided by the Washington State Department of Health, Oregon Department of Agriculture, and California Department of Public Health. 

**References**

::: {.sectionrefs}
:::
