# HMS Diets

**Description** Quantifying the diets of highly migratory fishes in the CCE can complement existing trawl-based assessments of the available forage, provide insight into how forage varies over time and space, as well as provide a direct metric of forage utilization. Albacore Tuna, Bluefin Tuna, and Broadbill Swordfish are opportunistic predators that consume a wide variety of prey taxa across a range of depths and habitats. Albacore, Bluefin, and Swordfish stomachs were provided by commercial and recreational fishers, and prey were identified from whole or hard part remains and are reported as a mean percent abundance. A subset of prey species are presented here focusing on prey that are either themselves under a management plan, or considered ecosystem component species, to highlight their links to highly migratory species. Juvenile Albacore Tuna were collected off Northern California, Oregon, and Washington during the summer and fall fishing season. Bluefin Tuna were collected by recreational fishers in the Southern California Bight from spring until early fall. Swordfish were collected off Southern and Central California during the commercial drift gillnet season (August 15th through January 31st). Swordfish stomachs are classified by the year the fishing season began (stomachs from January are assigned to the previous year’s fishing season).

\[need for descriptive text for figures?\]

**Data sources**

**Data extraction**

**Data analysis**
