# Northern California Current Forage
{{< include _setup.qmd >}}

**Description** The Northern CCE survey (known as the Juvenile Salmon Ocean Ecology Survey, JSOES) occurs in June and targets juvenile salmon in surface waters off Oregon and Washington [@morgan2019recent]. It also collects adult and juvenile (age 1+) pelagic forage fishes, market squid, and gelatinous zooplankton with regularity. A Nordic 264 rope trawl is towed for 15-30 min at approximately 6.5 km/hr. The gear is fished during daylight hours in near-surface (upper 20 m) waters, which is appropriate for targeting juvenile salmon.

Several other taxa (e.g., anchovy, sardine, herring and mackerels) collected by the June JSOES surface trawl are not considered to be sampled quantitatively due to their behavior (i.e., depth in the water column during daylight hours) and mesh size of sampling gear. Thus, we do not report catch-per-unit-effort (CPUE) of these species, rather noting them in terms of their relative prevalence - the proportion of stations where they were caught.

Pelagic forage data from the Northern CCE are provided by B. Burke, NMFS/NWFSC and C. Morgan, OSU/CIMRS. Data are derived from surface trawls taken during the NWFSC Juvenile Salmon & Ocean Ecosystem Survey (JSOES; https://www.fisheries.noaa.gov/west-coast/science-data/ocean-ecosystem-indicators-pacific-salmon-marine-survival-northern). Similarity analysis and cluster plot by A. Thompson, NMFS/SWFSC.


```{r}
#| echo: false
#| results: 'asis'
erddap_id=c('cciea_EI_FBN','cciea_EI_FPN')
cat("<b>Forage Biomass:</b>\n")
one_id_byquery(erddap_id[1],"Species")
cat("<b>Forage Prevalence:</b>\n")
one_id_byquery(erddap_id[2],"Species")
get_erddap_link(erddap_id)
```

**References**
