# Non-Fishery Income Diversification

**Description** 
Compared to many other professions, fishers face unusually high year-to-year variability in their income levels. Diversifying fishing income can help reduce income variability and reduce financial risk, but focusing solely on diversification opportunities within the fishery misses a potentially important form of financial risk reduction - income diversification from non-fishing occupations (i.e., livelihood diversification). Livelihood diversification may actually be a more effective form of financial risk reduction for fishing households if their non-fishing income streams are unaffected by changes in fishery productivity or profitability or if they can be actively increased when fishing income is low.

Levels and trends in non-fishery income diversification have not been presented previously due to a lack of regularly collected data on non-fishery income (NFI). To address this and other informational gaps, the NWFSC began periodically surveying West Coast fishing vessel owners on a triennial basis with surveys carried out in 2017, 2020, and 2023. Surveys were sent to all vessel owners with commercial revenue from West Coast fisheries (federal and state) the prior year. Response rates were around 50% in 2017 and 2020 with over 1400 surveys returned each year. The response rate in 2023 fell to 40% with 1163 surveys returned.

Among other questions, the surveys ask fishing vessel owners what percentage of their household income came from fishing versus non-fishing sources in the prior calendar year (e.g. 2022 for the 2023 survey) and also what percentage of the income they personally contribute to the household is from non-fishery sources. The survey also asks vessel owners that personally contributed NFI to their household what type of non-fishing work they did. @Treakle2023not  provides a detailed analysis of the survey data on non-fishing income from the 2017 and 2020 surveys.

**Indicator Category** Human Wellbeing

**Data Steward** Dan Holland; dan.holland at noaa.gov

**Institution** NOAA NWFSC/AFSC

**Additional Information**
The West Coast Fisheries Participation Survey tool can be accessed at the following link:
https://www.fisheries.noaa.gov/national/science-data/west-coast-fisheries-participation-survey-results


**References**
