# Salmon Stoplight Tables

**Description** 
Northern California Current; Columbia Basin stocks: We use color to represent anomalous years for the stoplight tables presented in the salmon section of the report. As described in Harvey et al. (2023), we have addressed past feedback from the SSC and others by developing a more statistically based stoplight table format, which produces five bins that are determined relative to a fixed baseline reference period. In this new format, we assumed a normal distribution for each of the indicators and estimated a mean and standard deviation for the base period. For each cell within a given indicator, we determined how many standard deviations the values were from their respective base period mean and used a five-color set to indicate whether a value was \>2 s.d. below the mean, 1 to 2 s.d. below the mean, within 1 s.d. of the mean in either direction, 1 to 2 s.d. above the mean, or \>2 s.d. above the mean. This approach overcomes many of the issues that had been previously identified (e.g., better highlighting values that represent truly exceptional years; past values are now static and do not suddenly change colors; etc.).

Central California Current; Klamath / Sacramento / Central Valley stocks:  The process of identifying key indicators for salmon habitat stoplight tables is ongoing (Munsch et al. in prep). To summarize our approach and findings to date, we used linear models to relate recruitment of SRFC, CVSC, and KRFC to salmon habitat indicators. In light of the potential for recruitment-indicator relationships to change over time, we selected indicators based on model performance metrics that suggested that the indicators were persistently or recently important to recruitment. Through preliminary analyses, we selected twelve key indicators, two of which are shared among the California Central Valley stocks (SRFC and CVSC) for a total of ten unique indicators. We note that we only found strong evidence for a linear relationship between natural spawners and future recruitment for SRFC (and thus use this indicator for forecasts below), but report natural spawner counts for other stocks for context. Our ongoing analyses will examine for evidence of a Ricker stock-recruitment relationship, which is not included here.

We also report new efforts to examine thiamine deficiency in hatchery eggs across the Central Valley in California. Some of the indicators we selected, particularly those relevant to SRFC, have been identified as important by previous research efforts [@friedman2019modeling; @munsch2020science; @munsch2022one]. Indicators were indexed according to brood year or outmigration year and then adjusted to return or fishing year via the assumptions that juveniles migrated the calendar year after their brood year and that most adults were harvested or returned as spawners three years after their brood year. 

\[this section will require a bit more writing to incorporate evolving approaches and methods\]

**Data sources**

**Data extraction**

**Data analysis**

**References**
