# Seabird Diet

**Description** Seabird diet .....

```{r get-file-from-google-drive}
#| echo: false
#| message: false
#| eval: true
source("_getmeta.R")
erddap_id <- c("cciea_B_AS_DIET","cciea_B_AS_DIET_ND")
sb_meta=getMetadata(erddap_id[1])
sb_private_meta=getMetadata(erddap_id[2])
meta <- rbind(sb_meta,sb_private_meta)
regions <- unique(meta['region'])
num_ind <- nrow(meta)
num_regions <- nrow(regions)
```

**Indicator Regions**
```{r}
#| echo: false
#| results: 'asis'

for (r in 1:num_regions){
  cat("**",regions$region[r],"**\n\n",sep="")
  
  cat("* <b>Species:</b>\n")
  for (i in 1:num_ind){
    if(meta$region[i]==regions$region[r]){
      cat("     + ",sub(".*?\\s", "",sub(".*C - ","",meta$Title[i])),"\n")
      cind=i
    }
    }
cat("* <b>Component Category: </b>", meta$Component_Section[cind],"\n")
cat("* <b>Data Steward: </b>",meta$Contact[cind],"\n")
cat("* <b>Institution: </b>",meta$Institution[cind],"\n")
cat("* <b>Source Data: </b>",meta$Source_Data[cind],"\n")
if(meta$Additional_Calculations[cind]!="")cat("* <b>Additional Calculations: </b>",meta$Additional_Calculations[cind],"\n\n")
}
```

**Data extraction**

```{r}
#| echo: false
#| results: 'asis'
cat("ERDDAP&trade; links: \n\n")
for(i in 1:length(erddap_id)){
  cat("<https://oceanview.pfeg.noaa.gov/erddap/tabledap/",erddap_id[i],".html> \n",sep="")
  }
```

**Data analysis**
