# Sea Lion Productivity
{{< include _setup.qmd >}}

**Description** 
California sea lion pup counts and pup growth rates are sensitive indicators of prey availability and composition in the Central and Southern CCE. 

*Pup count and pup growth as indicators of foraging conditions:* The San Miguel Island California sea lion indicators of pup births, pup condition, pup growth and nursing female diet are linked to the availability (a combination of abundance and distribution) and composition of the coastal pelagic forage community to nursing California sea lions foraging in the CCE from the northern California Channel Islands to Monterey Bay throughout the year. Nursing California sea lions are central place foragers for 11 months of the year, traveling to and from the breeding colonies in the Channel Islands, where their pups reside, to foraging areas within 200 km of the colonies. Consequently, they are sampling the coastal pelagic forage community throughout the year and their diet and resultant reproductive success measured by pup metrics depends on the availability of that forage community.

Nursing California sea lions consume a variety of fish and cephalopods but have a core diet of only seven taxa: Pacific hake, Pacific sardine, northern anchovy, rockfish, jack mackerel, Pacific mackerel, and market squid @melin2008effects; @melin2012california]. These taxa vary annually and seasonally in the diet. The nursing female diet index is based on the frequency of occurrence of these seven core taxa in scats collected at the San Miguel colony during the early lactation period (June-September). This index provides a relative measure of the availability of each prey taxa to nursing females within their foraging range because California sea lions consume prey relative to its abundance in the environment [@thompson2019indicators] but not necessarily proportionally. For example, an increase in the frequency of occurrence of anchovy from 5% in 1995 diets to 90% in 1996 diets means that almost no females consumed anchovy in 1995 because it was not available to them but almost all females consumed it in 1996; it does not necessarily mean that the biomass of anchovy increased nearly 20-fold in the CCE, just that the availability increased in the foraging range of nursing females. Nonetheless, it indicates that a change in the forage community occurred between the two years. A weakness of this index is that it only indicates presence or absence of a taxa in the diet; when sardine occurs in high frequency, it could be that sea lions are exploiting a small population of fish or it could be that sardine are ubiquitous in the environment. It also is a retrospective rather than forecasting index. It is thus important to view this as part of a suite of indicators about the prey community, along with ship-based catch or acoustic estimates of forage fish biomass. Strengths of the sea lion diet index are that it is easy to update annually and the core taxa comprise the core diet of many other top predators in the CCE that are difficult to sample or observe. Consequently, the annual variability and trends in the California sea lion diet can inform us on unusual patterns in the coastal pelagic forage community that may affect other top predators in the CCE.

Each of the pup indices in the report represents a different aspect of reproductive success that relies on successful foraging by reproductive females. As such, they are indirect qualitative measures of the forage available to reproductive females and do not provide specific forage community information. The annual number of pup births is an index of successful pregnancies, which are dependent on the nutritional condition of the female, which in turn, is dependent on the quality and quantity of prey available during the gestation period. Higher numbers of pup births indicates that females consumed a diet that provided sufficient quantity and nutrition to support the energetic cost of gestation. Pup condition and growth are dependent on milk intake. The more milk consumed the greater the better condition and growth rate. The amount of food consumed by a female on a foraging trip determines the amount of milk she has to deliver to the pup when she returns. Better pup condition and higher growth rates indicate abundant prey for nursing females during the lactation period.

Declines in pup births and pup growth have been associated with environmental events that reduced marine productivity at all trophic levels in the CCE for prolonged periods supporting the link between these indices and the status of the forage community [@delong1991effects; @iverson1991effect; @melin2010unprecedented; @melin2012age; @delong2017age]. Other factors such as diseases (e.g., hookworm, Lyons et al. 2005), immune suppression from pollution [@delong1973premature; @gilmartin1976premature] and natural environmental toxins [@goldstein2009role] may affect pup growth or births, but these factors are likely to have less of a population level effect than large-scale food supply issues that accompany anomalous oceanographic conditions.

*The influence of population abundance and carrying capacity on these indicators:* In discussions related to past reports, some Council advisory bodies expressed concerns that sea lion pup counts and growth may become less effective indicators when the population is close to carrying capacity, which it was in the 2010s: according to population modeling work by Laake et al. (2018), the San Miguel colony at that time had an estimated carrying capacity of ~275,000 animals (including pups), and annual population estimates between 2006 and 2014 ranged from 242,000 to 306,000 animals. Advisory bodies were concerned that changes in pup count or growth could be due to density dependent mechanisms within the sea lion population, rather than to changes in the prey community.

A linear mixed effects model of California sea lion pup growth that includes environmental variables, sea lion abundance, fish abundance and nursing female diet revealed that the abundance of California sea lions was not a significant factor in annual variability of pup growth rates (Melin et al. in preparation). The model also did not detect a declining trend in pup growth as the population size increased, which might occur if competition among nursing females for limited forage was affecting the ability of females to support the energetic demands of their pups. Elevated SST explained the greatest amount of variability for pup growth rates in the models: a 1°C increase in SST resulted in a 7% decline in the population growth rate, even when the population was much smaller (<100,000 animals) in the 1980s [@laake2018population]. The reverse effect was not apparent when SST decreased by 1°C. These analyses indicate that pup count and pup growth are not compromised as indicators by population size, but rather reflect the dynamic relationship between environmental conditions and California sea lion reproduction. We believe the key underlying mechanism is that elevated SST affects the distribution and abundance of the sea lion prey community thereby reducing access to food for nursing females, such that they cannot support the energetic demands of pregnancy, resulting in fewer births, or lactation, resulting in slower pup growth.

**2023 Methods Update**
To reduce disturbance to California sea lions and to improve the accuracy of our pup counts, we transitioned to using small drones (Aerial Imagery Systems' APH-28 and the Parrot Anafi) for our pup census in 2023. A pilot study in 2017 and 2018 that paired drone surveys and ground counts for the same areas showed no significant differences in counts determined from drones or ground counts. The drone surveys were flown at an altitude of 46 m over small or narrow sections of coastline or in transects over large areas. The images were stitched together using DigiKam software and pups were counted using DotDotGoose software that automatically entered the counts into a data file for analysis. In 2023, weather conditions precluded using the drones for the entire count so we conducted ground counts for about 20% of the colony and used drones for 80%.

**Indicators**

```{r}
#| echo: false
#| results: 'asis'
erddap_id='cciea_MM_pup_count'
one_id_multimeta(erddap_id)
get_erddap_link(erddap_id)
```

**References**
