# Spatial Interactions with Ocean-Use Sectors

**Description** 
Below, we describe two portfolios of indicators for i) oceanographic and lower-trophic level productivity and ii) fisheries activity that can help identify ocean areas important to the overall structure and function of the CCE, and that can track potential social-ecological impacts across all stages of OWE development.

Oceanography and Productivity. Six broad-scale indicators of long-term, spatial variation in oceanography and lower-trophic level productivity are being used to inform spatial suitability analyses in areas off northern California being considered for OWE development in 2024. The ecosystem indicators include: 1. Average wind-driven upwelling during March-July, calculated at 40m depth from 1988-2012 using the Regional Ocean Modeling System [@raghukumar2023projected]; 2. Long-term, spatial variability and hotspots in primary productivity, calculated from a biogeochemistry model as the average concentration of surface phytoplankton in May-July, 1995-2020 [@fiechter2018wind]; 3. Long-term, spatial variability and hotspots in secondary productivity from May-August, calculated as an ensemble of four different estimates of krill abundance/biomass across the West Coast [@cimino2020essential; @fiechter2020krill; @messie2022satellite; @phillips2022spatiotemporal]; 4. Long-term, spatial variability and hotspots for young-of-year (YOY) rockfishes during their pelagic juvenile life stage in May-June from 2001-2022 [@field2021spatiotemporal]; 5.Long-term, spatial variability and hotspots for YOY Pacific hake in May-June from 2001-2022 [@field2021spatiotemporal]; 6. Long-term, spatial variability and hotspots of groundfish nursery habitat on the seafloor, based on summed average densities of juveniles from 13 groundfish species in May-October from 2003-2018 [@tolimieri2020spatio].

**Indicator Category** Fishing and Non-Fishing Human Activities

**Data Steward** Andrews; kelly.andrews at noaa.gov

**Institution** NOAA NWFSC/SWFSC; WCR

**Additional Information**
Data are collected and analyzed independently by K. Andrews and team, who submit internally reviewed figures and plots to the CCIEA editorial team. 

The Bureau of Ocean Energy Management (BOEM) has been using a spatial suitability analysis developed by NOAA’s National Centers for Coastal and Ocean Science (NCCOS) to identify areas BOEM may consider for OWE development. In order to inform an analysis of new areas along the northern California coast, we used BOEM’s methods to calculate an overall suitability score across the six ecosystem indicators for each grid cell [@riley2021aquaculture]. Briefly, the raw data for each indicator was cropped to the area-of-interest, interpolated across a 2x2-km spatial grid, transformed using a z-membership function, and then geometrically averaged across all indicators for each grid cell. This geometric mean represents the suitability score of a grid cell for OWE development relative to the importance of these areas to the processes represented by each indicator; thus, a suitability score of ‘1’ is most suitable for OWE, while suitability scores closer to 0 are less suitable. In addition to being applicable to siting of new areas, these indicators could be used to establish baseline conditions that can be used to identify potential effects resulting from OWE development and to identify relevant mitigation strategies.

**Data sources**

*Fisheries Indicators*.* We developed seven indicators that describe spatial and temporal variation in groundfish bottom trawling activity from 2002-2021 in the same region being considered for OWE development off the coast of northern California. These indicators were presented in the 2022 ESR [@harvey2022cciea] and are meant to capture the spatial and temporal variation in fishing effort for the groundfish bottom trawl fishery and to be used in tandem with the ecosystem indicators to identify potential interactions across the entire social-ecological system.

For the groundfish indicators herein, we used logbook set and retrieval coordinates from the limited-entry/catch shares groundfish bottom trawl fisheries to estimate total duration trawled on a 2x2-km grid. These durations were then used to calculate: 1. total duration trawled in the most recent year (2021); 2. the anomaly of the most recent year relative to the entire time series; 3. the most recent 5-year mean (2017-2021); 4. the most recent 5-year trend (2017-2021); 5. the sum of duration trawled across all years; 6. the proportion of years trawled; and 7. the number of years since trawling occurred within each grid cell. 

To maintain confidentiality, grid cells with <3 vessels operating within the grid cell across the years associated with the indicator have been removed. The first four indicators are consistent with measuring the ‘status’ and ‘trends’ of other ecosystem indicators presented in this report, while the last three have been developed as indicators to use within a risk analysis framework. These indicators account for only federal limited-entry/catch shares groundfish bottom trawl fisheries from 2002-2021, but provide a useful framework for identifying the potential for overlap and conflict between day-to-day fisheries operations and OWE areas. Other fisheries were included in a similar framework and will be added as analyses are completed.

**References**

::: {.sectionrefs}
:::
