# Whale Entanglement
{{< include _setup.qmd >}}

**Description** 
The number of large whale entanglements confirmed by NOAA Fisheries has increased off the U.S. West Coast in recent years. This alarming pattern has mobilized efforts to understand and address factors that contribute to whale entanglement in fishing gear. The dynamics of entanglement risk and reporting are complex, and are affected by shifts in ocean conditions and prey fields, changes in whale populations, changes in distribution and timing of fishing effort, and increased public awareness.

NOAA Fisheries is responsible for recovering and protecting these whales under the Marine Mammal Protection Act and Endangered Species Act. The states are responsible for managing many of the fisheries that interact with these whales. 
Whale entanglement data is compiled by NOAA Fisheries West Coast Region. The CCIEA website (https://www.integratedecosystemassessment.noaa.gov/regions/california-current/the-ecosystem-context-reducing-west-coast-whale-entanglements) serves some of these data in an interactive map, which can be used to view the spatial distribution of entanglement records by species, gear type, and year.


**Indicators**

```{r}
#| echo: false
#| results: 'asis'
erddap_id='cciea_EI_WH_ENT'
one_id_byquery(erddap_id,"Species")
get_erddap_link(erddap_id)
```

**References**

::: {.sectionrefs}
:::
